//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapReader.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapReader.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [Events]
        /////Background and Video events
        /////Storyboard Layer 0 (Background)
        ///Sprite,Background,TopCentre,&quot;white.png&quot;,320,240
        /// M,0,-2000,,320,0
        /// C,0,-2000,,0,0,0
        /// V,0,-2000,,533.75,76
        /// F,0,-2000,45433,0.4
        /// F,0,45433,45948,0.4,0
        /// F,0,67376,67891,0,0.4
        /// V,2,67376,77148,533.75,30,533.75,120
        /// V,0,78519,,533.75,0
        /// F,0,122748,123434,0.4,0
        /// F,1,188576,189262,0,0.4
        /// F,2,209147,210519,0.4,0
        ///Sprite,Background,BottomCentre,&quot;white.png&quot;,320,240
        /// M,0,-2000,,320,480
        /// C,0,-2000,,0,0,0
        /// V,0,-2000,,533.75,30
        /// F [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string FarEastNightbird_osb {
            get {
                return ResourceManager.GetString("FarEastNightbird.osb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [Events]
        /////Background and Video events
        /////Storyboard Layer 0 (Background)
        ///Sprite,Background,Centre,&quot;dein traum wird wahr background.jpg&quot;,320,240
        /// F,0,0,,0
        ///Sprite,Background,Centre,&quot;sb\bg.jpg&quot;,320,240
        /// F,0,0,,1
        /// S,0,0,,0.8465608
        /// F,0,153653,,0
        /// F,0,153751,,0
        ///Sprite,Background,Centre,&quot;sb\bg monochrome.jpg&quot;,320,240
        /// F,0,0,,1
        /// S,0,0,,0.8465608
        /// F,0,12,13992,1,0.4
        /// F,0,13993,14393,0.4,0
        /// S,0,13993,14393,0.8465608,0.8888889
        ///Sprite,Background,Centre,&quot;sb\bg monochrome.jpg&quot;,320,240
        /// S,0,144478,,0.846 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Vanilla_osb {
            get {
                return ResourceManager.GetString("Vanilla.osb", resourceCulture);
            }
        }
    }
}
